import Logo from "./Logo.png";
import WelcomeImg from "./WellcomeImg.png";
import AboutUsImg from "./aboutUs.png";
import OurStudentsImg from "./OurStudentImg.png";
import Profileimg from "./profileimg.png";
import FacebookIcon from "./facebook.png";
import EmailIcon from "./email.png";
import twitterIcon from "./twitter.png";
import WhatsAppIcon from "./whatsapp.png";
import InstaGramIcon from "./instagram.png";
import LoginTexture from "./loginTexture.png";
import UserIcon from "./userIcon.svg";
import PasswordIcon from "./passwordIcon.svg";
import FacebookLogo from "./facebookLogo.png";
import GoogleLogo from "./googleLogo.png";
import DemoImg from "./demoImg.png";
import AiAssisstant from "./aiAssisstant.png";
import Presentaition from "./presentaition.png";
import RealScenario from "./realscenario.png";
import ToDoList from "./ToDoList.png";
import TimeImg from "./timeimg.png";
import TrophyImg from "./trophyimg.png";
import Rankimg from "./Rankimg.png";
import Languageimg from "./languageimg.png";
import Robot from "./ropot.png";
import Send from "./send.png";
import SceneImg from "./SceneImg.png";
import ActiveLevel from "./ActiveLevel.png";
import DisactiveLevel from "./DisactiveLevel.png";
import NewWorld from "./NewWorld.png";
import Heart from "./Heart.png";

export { Logo };
export { WelcomeImg };
export { AboutUsImg };
export { OurStudentsImg };
export { Profileimg };
export { FacebookIcon, EmailIcon, twitterIcon, WhatsAppIcon, InstaGramIcon };
export { LoginTexture };
export { UserIcon, PasswordIcon };
export { FacebookLogo, GoogleLogo };
export { DemoImg };
export { AiAssisstant, Presentaition, RealScenario };
export { ToDoList };
export { TimeImg, TrophyImg, Languageimg, Rankimg };
export { Robot };
export { Send };
export { SceneImg, ActiveLevel, DisactiveLevel };
export { NewWorld, Heart };
